---
sudo: false
language: rust
rust:
  - stable

install:
  # Modified from https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/use-conda-with-travis-ci.html
  - sudo apt-get update
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  - conda config --add channels defaults
  - conda config --add channels bioconda
  - conda config --add channels conda-forge

  - conda create -q -n test-environment bwa-mem2 'samtools>=1.9' 'minimap2>=2.20' 'dashing>=0.4.0' 'fastani>=1.3'
  - source activate test-environment
  - cargo build --verbose

  - export PATH=target/debug:$PATH

cache: cargo

os:
  - linux

env:
  - ARCH=x86_64

build: false

test_script:
  - export PATH=target/debug:$PATH
  - cargo test

